import {supabase} from '../lib/supabase';
import type {ShinobiCharacter} from './characterService';
import type {MatchupAnalysis,MatchupRecord,ShinobiRival,ShinobiTeam,ShinobiTeamMember} from '../types/social';

export async function listTeams(userId:string){if(!supabase)return[];const {data,error}=await supabase.from('shinobi_teams').select('*').eq('user_id',userId).order('updated_at',{ascending:false});if(error)throw error;return(data??[]) as ShinobiTeam[]}
export async function createTeam(userId:string,name:string){if(!supabase)throw new Error('Supabase not configured');const clean=name.trim().slice(0,60)||'New Squad';const {data,error}=await supabase.from('shinobi_teams').insert({user_id:userId,name:clean}).select('*').single();if(error)throw error;return data as ShinobiTeam}
export async function deleteTeam(userId:string,teamId:string){if(!supabase)return;const {error}=await supabase.from('shinobi_teams').delete().eq('id',teamId).eq('user_id',userId);if(error)throw error}
export async function updateTeam(userId:string,teamId:string,name:string,description:string){if(!supabase)throw new Error('Supabase not configured');const {data,error}=await supabase.from('shinobi_teams').update({name:name.trim().slice(0,60)||'Squad',description:description.trim().slice(0,280)||null,updated_at:new Date().toISOString()}).eq('id',teamId).eq('user_id',userId).select('*').single();if(error)throw error;return data as ShinobiTeam}
export async function listTeamMembers(teamId:string){if(!supabase)return[];const {data,error}=await supabase.from('shinobi_team_members').select('*, character:shinobi_characters(*)').eq('team_id',teamId).order('position');if(error)throw error;return(data??[]) as ShinobiTeamMember[]}
export async function addTeamMember(teamId:string,characterId:string){if(!supabase)throw new Error('Supabase not configured');const {error}=await supabase.rpc('add_shinobi_team_member_v10',{p_team_id:teamId,p_character_id:characterId});if(error)throw error}
export async function removeTeamMember(memberId:string){if(!supabase)return;const {error}=await supabase.from('shinobi_team_members').delete().eq('id',memberId);if(error)throw error}
export async function addRival(userId:string,characterId:string,rivalCharacterId:string,note=''){if(!supabase)throw new Error('Supabase not configured');const {data,error}=await supabase.from('shinobi_rivals').upsert({user_id:userId,character_id:characterId,rival_character_id:rivalCharacterId,note:note.trim().slice(0,200)||null},{onConflict:'user_id,character_id,rival_character_id'}).select('*').single();if(error)throw error;return data as ShinobiRival}
export async function listRivals(userId:string,characterId?:string){if(!supabase)return[];let q=supabase.from('shinobi_rivals').select('*, character:shinobi_characters!shinobi_rivals_character_id_fkey(*), rival:shinobi_characters!shinobi_rivals_rival_character_id_fkey(*)').eq('user_id',userId).order('created_at',{ascending:false});if(characterId)q=q.eq('character_id',characterId);const {data,error}=await q;if(error)throw error;return(data??[]) as ShinobiRival[]}
export async function removeRival(userId:string,id:string){if(!supabase)return;const {error}=await supabase.from('shinobi_rivals').delete().eq('id',id).eq('user_id',userId);if(error)throw error}
export async function saveMatchup(userId:string,left:ShinobiCharacter,right:ShinobiCharacter,analysis:MatchupAnalysis){if(!supabase)return null;const {data,error}=await supabase.from('shinobi_matchups').insert({user_id:userId,left_character_id:left.id,right_character_id:right.id,winner_character_id:analysis.winnerId,analysis}).select('*').single();if(error)throw error;return data as MatchupRecord}
export async function listMatchups(userId:string,limit=20){if(!supabase)return[];const {data,error}=await supabase.from('shinobi_matchups').select('*').eq('user_id',userId).order('created_at',{ascending:false}).limit(limit);if(error)throw error;return(data??[]) as MatchupRecord[]}
