import {useEffect,useMemo,useState} from 'react';import {useNavigate} from 'react-router-dom';import {useArchive} from '../store/useArchive';import {useAuth} from '../contexts/AuthContext';import {normalizeProfile} from '../utils/characterProfile';import {deriveCombatStats,statLabels} from '../utils/combatStats';import {generateTechnique} from '../utils/jutsuGenerator';import {deleteJutsu,listJutsu,saveJutsu,setJutsuSlot} from '../services/jutsuService';import type {JutsuSlot,JutsuTechnique} from '../types/combat';
const slots:JutsuSlot[]=['standard','advanced','signature','ultimate','summoning'];
export function ArsenalPage(){const nav=useNavigate();const {user}=useAuth();const {name,activeCharacterId,results}=useArchive();const profile=useMemo(()=>normalizeProfile(name,activeCharacterId,results),[name,activeCharacterId,results]);const stats=useMemo(()=>deriveCombatStats(profile),[profile]);const [jutsu,setJutsu]=useState<JutsuTechnique[]>([]);const [preview,setPreview]=useState<JutsuTechnique|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const refresh=async()=>{if(user&&activeCharacterId)try{setJutsu(await listJutsu(user.id,activeCharacterId))}catch(e){setError(e instanceof Error?e.message:'Could not load jutsu')}};useEffect(()=>{void refresh()},[user?.id,activeCharacterId]);
 const generate=()=>setPreview(generateTechnique(profile,jutsu.length)); const save=async()=>{if(!preview||!user||!activeCharacterId)return;setBusy(true);try{await saveJutsu(user.id,activeCharacterId,preview);setPreview(null);await refresh()}catch(e){setError(e instanceof Error?e.message:'Could not save technique')}finally{setBusy(false)}};
 if(!activeCharacterId)return <div className="screen"><h2>Open a shinobi first</h2><p className="lede">V10 stats and jutsu belong to a specific saved shinobi.</p><button className="btn primary" onClick={()=>nav('/account')}>Open My Shinobi</button></div>;
 return <div className="screen arsenal-page page-enter"><div className="dash-head"><div><span className="eyebrow">V10 · ARSENAL</span><h2>{name}'s Combat Archive</h2></div><p>Derived stats use your completed identity trials. Jutsu are generated from the active shinobi's actual clan, chakra, fighting style, specialty and rank potential.</p></div>{error&&<div className="generator-error">{error}</div>}
 <section className="box"><div className="section-title"><div><span className="eyebrow">DERIVED PROFILE</span><h3>Combat Stats</h3></div><span>{profile.completion}% identity</span></div><div className="stat-grid">{Object.entries(stats).map(([k,v])=><div className="stat-row" key={k}><span>{statLabels[k as keyof typeof statLabels]}</span><div className="stat-track"><i style={{width:`${v}%`}}/></div><strong>{v}</strong></div>)}</div></section>
 <section className="box"><div className="section-title"><div><span className="eyebrow">TECHNIQUE FORGE</span><h3>Generate Jutsu</h3></div><button className="btn primary" onClick={generate}>Generate Technique</button></div>{preview?<article className="jutsu-card featured"><div className="jutsu-head"><div><span className="eyebrow">{preview.rank}-RANK · {preview.type}</span><h3>{preview.name}</h3></div><b>{preview.chakraNature}</b></div><p>{preview.description}</p><div className="jutsu-meta"><span>Range · {preview.range}</span><span>Role · {preview.role}</span><span>Cost · {preview.chakraCost}</span></div><div className="jutsu-columns"><div><strong>Strengths</strong>{preview.strengths.map(x=><span key={x}>+ {x}</span>)}</div><div><strong>Weaknesses</strong>{preview.weaknesses.map(x=><span key={x}>− {x}</span>)}</div></div><div className="cloud-card-actions"><button className="btn primary" disabled={!user||busy} onClick={save}>{user?'Save to Shinobi':'Sign in to save'}</button><button className="btn ghost" onClick={generate}>Reroll</button></div></article>:<p className="muted">Generate a technique to preview it here.</p>}</section>
 <section className="box"><div className="section-title"><div><span className="eyebrow">SAVED ARSENAL</span><h3>Technique Loadout</h3></div><span>{jutsu.length} saved</span></div><div className="jutsu-grid">{jutsu.map(j=><article className="jutsu-card" key={j.id}><div className="jutsu-head"><div><span className="eyebrow">{j.rank}-RANK · {j.type}</span><h3>{j.name}</h3></div>{j.slot&&<b>{j.slot.toUpperCase()}</b>}</div><p>{j.description}</p><div className="jutsu-meta"><span>{j.chakraNature}</span><span>{j.range}</span><span>{j.chakraCost}</span></div><label className="slot-select">Loadout slot <select value={j.slot||''} onChange={async e=>{if(!user||!activeCharacterId)return;await setJutsuSlot(j.id,user.id,activeCharacterId,(e.target.value||null) as JutsuSlot|null);await refresh()}}><option value="">Unequipped</option>{slots.map(s=><option key={s} value={s}>{s}</option>)}</select></label><button className="mini-link danger" onClick={async()=>{if(!user)return;await deleteJutsu(j.id,user.id);await refresh()}}>Delete</button></article>)}{!jutsu.length&&<p className="muted">No saved techniques yet.</p>}</div></section></div>}
