import {useEffect,useMemo,useState} from 'react';import type {ReactNode} from 'react';import {useNavigate} from 'react-router-dom';import {useArchive} from '../store/useArchive';import {useAuth} from '../contexts/AuthContext';import {normalizeProfile} from '../utils/characterProfile';import {deriveCombatStats} from '../utils/combatStats';import {generateMission,resolveMission} from '../utils/missionGenerator';import {levelFromXp,operationalRank,progressionAchievements,reputationTitle,xpForLevel,xpForNextLevel} from '../utils/missionProgression';import {abandonMission,acceptMission,completeMission,getProgression,listMissions} from '../services/missionService';import type {ShinobiMission,ShinobiProgression} from '../types/progression';
export function MissionsPage(){const nav=useNavigate();const {user}=useAuth();const {name,activeCharacterId,results}=useArchive();const profile=useMemo(()=>normalizeProfile(name,activeCharacterId,results),[name,activeCharacterId,results]);const stats=useMemo(()=>deriveCombatStats(profile),[profile]);const [prog,setProg]=useState<ShinobiProgression|null>(null);const [missions,setMissions]=useState<ShinobiMission[]>([]);const [offer,setOffer]=useState<ShinobiMission|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const refresh=async()=>{if(!user||!activeCharacterId)return;try{const[p,m]=await Promise.all([getProgression(user.id,activeCharacterId),listMissions(user.id,activeCharacterId)]);setProg({...p,level:levelFromXp(p.xp)});setMissions(m)}catch(e){setError(e instanceof Error?e.message:'Could not load mission record')}};useEffect(()=>{void refresh()},[user?.id,activeCharacterId]);
 if(!activeCharacterId)return <div className="screen"><h2>Open a shinobi first</h2><p className="lede">Missions and progression belong to a specific saved shinobi.</p><button className="btn primary" onClick={()=>nav('/account')}>Open My Shinobi</button></div>;
 if(!user)return <div className="screen"><h2>Sign in to deploy</h2><p className="lede">Mission progression is saved to your V10 account.</p><button className="btn primary" onClick={()=>nav('/login')}>Sign In</button></div>;
 const p=prog;const level=p?.level??1;const rank=p?operationalRank(p,profile):'Genin';const badges=p?progressionAchievements(p):[];const currentFloor=xpForLevel(level),next=xpForNextLevel(level),levelPct=Math.max(2,Math.min(100,Math.round(((p?.xp??0)-currentFloor)/Math.max(1,next-currentFloor)*100)));const active=missions.find((m:ShinobiMission)=>m.status==='accepted');const history=missions.filter((m:ShinobiMission)=>m.status==='completed'||m.status==='failed');
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();await refresh()}catch(e){setError(e instanceof Error?e.message:'Mission action failed')}finally{setBusy(false)}};
 return <div className="screen missions-page page-enter"><div className="dash-head"><div><span className="eyebrow">V10 · PHASE 2</span><h2>{name}'s Mission Command</h2></div><p>Deploy your active shinobi, earn XP, build village reputation, and progress through operational ranks.</p></div>{error&&<div className="generator-error">{error}</div>}
 <section className="mission-summary"><div><span>LEVEL</span><strong>{level}</strong><small>{p?.xp??0} XP</small></div><div><span>OPERATIONAL RANK</span><strong>{rank}</strong><small>{profile.rankPotential||'Potential unknown'}</small></div><div><span>VILLAGE REPUTATION</span><strong>{p?.village_reputation??0}</strong><small>{reputationTitle(p?.village_reputation??0)}</small></div><div><span>MISSIONS</span><strong>{p?.completed_missions??0}</strong><small>{p?.s_missions??0} S · {p?.a_missions??0} A · {p?.b_missions??0} B</small></div></section>
 <section className="box"><div className="section-title"><div><span className="eyebrow">LEVEL PROGRESSION</span><h3>Field Experience</h3></div><span>{levelPct}% to Lv. {level+1}</span></div><div className="mission-xp"><i style={{width:`${levelPct}%`}}/></div><div className="badge-row">{badges.map(b=><div className={`badge ${b.earned?'earned':''}`} key={b.id} title={b.description}><b>{b.icon}</b><span>{b.label}</span></div>)}</div></section>
 <section className="box"><div className="section-title"><div><span className="eyebrow">MISSION BOARD</span><h3>{active?'Active Deployment':'Request Assignment'}</h3></div>{!active&&<button className="btn primary" onClick={()=>setOffer(generateMission(profile,stats,level,Date.now()))}>Generate Mission</button>}</div>{active?<MissionCard mission={active} action={<><button className="btn primary" disabled={busy} onClick={()=>run(async()=>{const r=resolveMission(active,profile,stats);await completeMission(user.id,active,r.outcome,r.success)})}>Resolve Mission</button><button className="btn ghost" disabled={busy} onClick={()=>run(()=>abandonMission(user.id,active.id))}>Abandon</button></>}/>:offer?<MissionCard mission={offer} action={<><button className="btn primary" disabled={busy} onClick={()=>run(async()=>{await acceptMission(user.id,activeCharacterId,offer);setOffer(null)})}>Accept Mission</button><button className="btn ghost" onClick={()=>setOffer(generateMission(profile,stats,level,Date.now()+Math.random()*99999))}>Reroll</button></>}/>:<p className="muted">Generate an assignment matched to your current level and identity profile.</p>}</section>
 <section className="box"><div className="section-title"><div><span className="eyebrow">FIELD RECORD</span><h3>Mission History</h3></div><span>{history.length} recorded</span></div><div className="mission-history">{history.map((m:ShinobiMission)=><article key={m.id}><b className={`mission-rank rank-${m.rank.toLowerCase()}`}>{m.rank}</b><div><strong>{m.title}</strong><span>{m.category} · {m.location}</span><p>{m.outcome||m.objective}</p></div><em className={m.status}>{m.status.toUpperCase()}</em></article>)}{!history.length&&<p className="muted">No completed missions yet.</p>}</div></section></div>}
function MissionCard({mission,action}:{mission:ShinobiMission;action:ReactNode}){return <article className="mission-card"><div className="mission-card-head"><b className={`mission-rank rank-${mission.rank.toLowerCase()}`}>{mission.rank}</b><div><span className="eyebrow">{mission.category.toUpperCase()} · {mission.location.toUpperCase()}</span><h3>{mission.title}</h3></div></div><p>{mission.briefing}</p><div className="mission-objective"><span>OBJECTIVE</span><strong>{mission.objective}</strong></div><div className="mission-traits">{mission.recommended_traits.map(x=><span key={x}>{x}</span>)}</div><div className="mission-rewards"><div><span>XP</span><b>+{mission.rewards.xp}</b></div><div><span>REPUTATION</span><b>+{mission.rewards.reputation}</b></div>{mission.rewards.badge&&<div><span>BADGE</span><b>{mission.rewards.badge}</b></div>}</div><div className="cloud-card-actions">{action}</div></article>}
