import {useEffect,useMemo,useState} from 'react';
import {useNavigate,useSearchParams} from 'react-router-dom';
import {useAuth} from '../contexts/AuthContext';
import {useArchive} from '../store/useArchive';
import {listCharacters,listPublicCharacters} from '../features/characters';
import {addRival,addTeamMember,analyzeMatchup,analyzeTeam,applyInteractiveBattleResult,characterCombatant,createTeam,deleteTeam,listMatchups,listRivals,listTeamMembers,listTeams,removeRival,removeTeamMember,saveMatchup,updateTeam} from '../features/social';
import {deployTeamOperation,deployVillageWarTeam,getActiveVillageWar,listTeamOperations,listVillageWarDeployments,listVillageWarStandings} from '../features/warfare';
import {listJutsu} from '../features/arsenal';
import {effectiveCombatStats,getTrainingProfile,listEquipment} from '../features/training';
import type {MatchupAnalysis,MatchupRecord,MissionRank,ShinobiCharacter,ShinobiRival,ShinobiTeam,ShinobiTeamMember,TeamOperation,VillageWarDeployment,VillageWarSeason,VillageWarStanding} from '../types';
import {Feedback,errorMessage,useAsyncAction} from '../lib/app';
import {EmptyMessage,PageHeader,SectionHeader,SocialTabs} from '../lib/ui';
import {ActivityChallenge,CombatEncounter,type ActivityResult,type CombatOpponent,type CombatResult} from '../lib/minigames';


function opponentFromCharacter(character:ShinobiCharacter):CombatOpponent{
 const stats=characterCombatant(character).stats;
 const power=Math.round((stats.ninjutsu+stats.taijutsu+stats.speed+stats.chakraControl+stats.adaptability)/5);
 const styleText=`${character.role||''} ${character.specialization||''} ${character.leadership||''}`.toLowerCase();
 const affinity=styleText.includes('assault')||styleText.includes('close')?'pressure':styleText.includes('control')||styleText.includes('recon')||styleText.includes('precision')?'control':'adaptive';
 return {name:character.shinobi_alias||character.name,style:character.specialization||character.role||'Adaptive Shinobi',detail:`${character.clan||'Unknown clan'} · ${character.village||'Independent'} · ${character.chakra_primary||'neutral'} chakra`,power,affinity,technique:`${character.chakra_primary||'Chakra'} Style Technique`,element:character.chakra_primary||undefined,hp:Math.round(92+stats.stamina*.22),chakra:Math.round(92+stats.chakraControl*.2),portraitUrl:character.portrait_url};
}

async function loadOwnedBattleBuild(userId:string,character:ShinobiCharacter){
 const base=characterCombatant(character).stats;
 const [training,equipment,jutsu]=await Promise.all([getTrainingProfile(character.id),listEquipment(character.id),listJutsu(userId,character.id)]);
 return {stats:effectiveCombatStats(base,training,equipment),jutsu,equipment};
}

export function TeamsPage(){
 const {user}=useAuth();const nav=useNavigate();const {activeCharacterId}=useArchive();
 const [teams,setTeams]=useState<ShinobiTeam[]>([]);const [selectedId,setSelectedId]=useState<string>('');const [members,setMembers]=useState<ShinobiTeamMember[]>([]);const [own,setOwn]=useState<ShinobiCharacter[]>([]);const [publicChars,setPublicChars]=useState<ShinobiCharacter[]>([]);const [name,setName]=useState('');const [description,setDescription]=useState('');const [candidate,setCandidate]=useState('');const action=useAsyncAction('Team action failed');
 const selected=teams.find(t=>t.id===selectedId)||null;
 const refreshTeams=async()=>{if(!user)return;const next=await listTeams(user.id);setTeams(next);if(!selectedId&&next[0])setSelectedId(next[0].id)};
 const refreshMembers=async()=>{if(!selectedId){setMembers([]);return;}setMembers(await listTeamMembers(selectedId))};
 useEffect(()=>{if(!user)return;Promise.all([listTeams(user.id),listCharacters(user.id),listPublicCharacters(40)]).then(([t,o,p])=>{setTeams(t);setOwn(o);setPublicChars(p);const id=t[0]?.id||'';setSelectedId(id)}).catch(e=>action.setError(errorMessage(e,'Could not load teams')))},[user?.id]);
 useEffect(()=>{void refreshMembers()},[selectedId]);
 useEffect(()=>{if(selected){setName(selected.name);setDescription(selected.description||'')}},[selected?.id]);
 const analysis=useMemo(()=>analyzeTeam(members.flatMap(m=>m.character?[characterCombatant(m.character)]:[])),[members]);
 const available=useMemo(()=>{const ids=new Set(members.map(m=>m.character_id));const merged=[...own,...publicChars.filter(p=>!own.some(o=>o.id===p.id))];return merged.filter(c=>!ids.has(c.id))},[own,publicChars,members]);
 const run=(fn:()=>Promise<void>,success?:string)=>action.run(fn,{after:async()=>{await refreshTeams();await refreshMembers()},success});
 if(!user)return <div className="screen"><h2>Sign in to build squads</h2><p className="lede">Teams, rivals and matchup history belong to your account.</p><button className="btn primary" onClick={()=>nav('/login')}>Sign In</button></div>;
 return <div className="screen social-page page-enter"><PageHeader eyebrow="V11 · SOCIAL" title="Shinobi Teams" description="Build squads from your own shinobi and public profiles. V11 analyzes coverage, cohesion, battlefield roles, cooperative operations, and war-readiness."/><Feedback error={action.error} notice={action.notice}/>
 <SocialTabs active="teams"/>
 <div className="team-layout"><aside className="box team-sidebar"><div className="section-title"><div><span className="eyebrow">YOUR SQUADS</span><h3>{teams.length} Teams</h3></div><button className="mini-link" onClick={()=>run(async()=>{const t=await createTeam(user.id,`Squad ${teams.length+1}`);setSelectedId(t.id)},'New squad created.')}>+ New</button></div>{teams.map(t=><button className={`team-select ${selectedId===t.id?'active':''}`} key={t.id} onClick={()=>setSelectedId(t.id)}><strong>{t.name}</strong><span>{t.description||'No description yet'}</span></button>)}{!teams.length&&<p className="muted">Create your first squad.</p>}</aside>
 <div className="team-main">{selected?<><section className="box"><div className="section-title"><div><span className="eyebrow">SQUAD PROFILE</span><h3>{selected.name}</h3></div><button className="mini-link danger" onClick={()=>{if(confirm(`Delete ${selected.name}?`))void run(async()=>{await deleteTeam(user.id,selected.id);setSelectedId('')})}}>Delete</button></div><div className="team-editor"><input value={name} maxLength={60} onChange={e=>setName(e.target.value)} placeholder="Squad name"/><textarea value={description} maxLength={280} onChange={e=>setDescription(e.target.value)} placeholder="Squad purpose or description…"/><button className="btn secondary" disabled={action.busy} onClick={()=>run(async()=>{await updateTeam(user.id,selected.id,name,description)},'Squad updated.')}>Save Squad</button></div></section>
 <section className="box"><div className="section-title"><div><span className="eyebrow">MEMBERS</span><h3>{members.length}/4 Shinobi</h3></div></div><div className="team-member-grid">{members.map((m,i)=><article className="team-member" key={m.id}><div className="team-member-avatar">{m.character?.portrait_url?<img src={m.character.portrait_url} alt=""/>:<span>忍</span>}</div><div><small>SLOT {i+1}</small><h4>{m.character?.name||'Unknown Shinobi'}</h4><p>{[m.character?.clan,m.character?.village,m.character?.role].filter(Boolean).join(' · ')}</p></div><button className="mini-link danger" onClick={()=>run(async()=>{await removeTeamMember(m.id)})}>Remove</button></article>)}{members.length<4&&<div className="team-add"><select value={candidate} onChange={e=>setCandidate(e.target.value)}><option value="">Choose shinobi…</option>{available.map(c=><option value={c.id} key={c.id}>{c.name}{c.user_id===user.id?' · Mine':' · Public'}</option>)}</select><button className="btn primary" disabled={!candidate||action.busy} onClick={()=>run(async()=>{await addTeamMember(selected.id,candidate);setCandidate('')},'Shinobi added to squad.')}>Add Member</button></div>}</div></section>
 {members.length>0&&<section className="box"><div className="section-title"><div><span className="eyebrow">SQUAD ANALYSIS</span><h3>Team Readout</h3></div><strong>{analysis.rating}/100</strong></div><div className="team-metrics"><div><span>COHESION</span><strong>{analysis.cohesion}</strong></div><div><span>COVERAGE</span><strong>{analysis.coverage}</strong></div><div><span>LEADERSHIP</span><strong>{analysis.leadership}</strong></div></div><div className="team-analysis-grid"><div><h4>Strengths</h4>{analysis.strengths.map(x=><p key={x}>+ {x}</p>)}</div><div><h4>Pressure Points</h4>{analysis.weaknesses.map(x=><p key={x}>− {x}</p>)}</div></div><div className="role-list"><h4>Suggested Roles</h4>{analysis.roleAssignments.map(r=><div key={r.characterId}><strong>{r.name}</strong><span>{r.role}</span></div>)}</div></section>}</>:<div className="box"><h3>Create a squad</h3><p className="muted">Add up to four shinobi and V11 will analyze the team's composition.</p></div>}</div></div>
 </div>
}

export function RivalsPage(){
 const {user}=useAuth();const nav=useNavigate();const {activeCharacterId}=useArchive();
 const [own,setOwn]=useState<ShinobiCharacter[]>([]);const [pub,setPub]=useState<ShinobiCharacter[]>([]);const [rivals,setRivals]=useState<ShinobiRival[]>([]);
 const [characterId,setCharacterId]=useState(activeCharacterId||'');const [rivalId,setRivalId]=useState('');const [note,setNote]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const [battle,setBattle]=useState<{left:ShinobiCharacter;right:ShinobiCharacter;stats:ReturnType<typeof characterCombatant>['stats'];jutsu:Awaited<ReturnType<typeof listJutsu>>;equipment:Awaited<ReturnType<typeof listEquipment>>}|null>(null);
 const refresh=async()=>{if(!user)return;const [o,p,r]=await Promise.all([listCharacters(user.id),listPublicCharacters(60),listRivals(user.id)]);setOwn(o);setPub(p);setRivals(r);if(!characterId&&o[0])setCharacterId(o[0].id)};
 useEffect(()=>{void refresh()},[user?.id]);
 const available=useMemo(()=>pub.filter(c=>c.id!==characterId&&!rivals.some(r=>r.character_id===characterId&&r.rival_character_id===c.id)),[pub,rivals,characterId]);
 const fight=async(rival:ShinobiRival)=>{if(!user||!rival.character||!rival.rival)return;try{setError('');setNotice('');const build=await loadOwnedBattleBuild(user.id,rival.character);setBattle({left:rival.character,right:rival.rival,...build})}catch(e){setError(errorMessage(e,'Could not prepare rival battle.'))}};
 if(!user)return <div className="screen"><h2>Sign in to track rivals</h2><button className="btn primary" onClick={()=>nav('/login')}>Sign In</button></div>;
 return <div className="screen social-page page-enter">
  {battle&&<CombatEncounter title={`${battle.left.name} vs ${battle.right.name}`} opponent={opponentFromCharacter(battle.right)} stats={battle.stats} jutsu={battle.jutsu} equipment={battle.equipment} summon={battle.left.summon||undefined} playerElement={battle.left.chakra_primary||undefined} difficulty={72} onCancel={()=>setBattle(null)} onComplete={async(result:CombatResult)=>{const current=battle;setBattle(null);try{const analysis=applyInteractiveBattleResult(current.left,current.right,current.left.id,result);await saveMatchup(user.id,current.left,current.right,analysis);setNotice(`${analysis.winnerName} won the rival battle in ${result.rounds} rounds.`)}catch(e){setError(errorMessage(e,'Battle finished, but the result could not be saved.'))}}}/>} 
  <PageHeader eyebrow="V11 · SOCIAL" title="Rival Registry" description="Declare public rivals, analyze profile advantages, then settle the rivalry in live tactical combat."/>
  {error&&<div className="generator-error">{error}</div>}{notice&&<div className="generator-notice">{notice}</div>}<SocialTabs active="rivals"/>
  <section className="box"><SectionHeader eyebrow="DECLARE RIVAL" title="Create a Rivalry"/><div className="rival-builder"><select value={characterId} onChange={e=>setCharacterId(e.target.value)}>{own.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><span>VS</span><select value={rivalId} onChange={e=>setRivalId(e.target.value)}><option value="">Choose public rival…</option>{available.map(c=><option key={c.id} value={c.id}>{c.name} · {c.village||'Unknown Village'}</option>)}</select><input value={note} maxLength={200} onChange={e=>setNote(e.target.value)} placeholder="Why are they rivals? (optional)"/><button className="btn primary" disabled={!characterId||!rivalId} onClick={async()=>{try{await addRival(user.id,characterId,rivalId,note);setRivalId('');setNote('');await refresh()}catch(e){setError(errorMessage(e,'Could not add rival'))}}}>Declare Rival</button></div></section>
  <section className="box"><SectionHeader eyebrow="RIVALRIES" title={`${rivals.length} Active`}/><div className="rival-grid">{rivals.map(r=><article className="rival-card" key={r.id}><div className="rival-side"><strong>{r.character?.name||'Your Shinobi'}</strong><small>{r.character?.clan||'Unknown Clan'}</small></div><b>VS</b><div className="rival-side"><strong>{r.rival?.name||'Public Rival'}</strong><small>{r.rival?.clan||'Unknown Clan'}</small></div>{r.note&&<p>{r.note}</p>}<div className="public-actions"><button className="btn primary" disabled={!r.character||!r.rival} onClick={()=>void fight(r)}>Fight Rival</button><button className="btn secondary" onClick={()=>nav(`/matchups?left=${r.character_id}&right=${r.rival_character_id}`)}>Analyze Matchup</button><button className="btn ghost danger" onClick={async()=>{await removeRival(user.id,r.id);await refresh()}}>Remove</button></div></article>)}{!rivals.length&&<EmptyMessage>No rivalries declared yet.</EmptyMessage>}</div></section>
 </div>;
}

export function MatchupsPage(){
 const {user}=useAuth();const nav=useNavigate();const [params]=useSearchParams();
 const [own,setOwn]=useState<ShinobiCharacter[]>([]);const [pub,setPub]=useState<ShinobiCharacter[]>([]);const [leftId,setLeftId]=useState(params.get('left')||'');const [rightId,setRightId]=useState(params.get('right')||'');
 const [analysis,setAnalysis]=useState<MatchupAnalysis|null>(null);const [history,setHistory]=useState<MatchupRecord[]>([]);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const [battle,setBattle]=useState<{left:ShinobiCharacter;right:ShinobiCharacter;player:ShinobiCharacter;opponent:ShinobiCharacter;stats:ReturnType<typeof characterCombatant>['stats'];jutsu:Awaited<ReturnType<typeof listJutsu>>;equipment:Awaited<ReturnType<typeof listEquipment>>}|null>(null);
 useEffect(()=>{if(!user)return;Promise.all([listCharacters(user.id),listPublicCharacters(80),listMatchups(user.id)]).then(([o,p,h])=>{setOwn(o);setPub(p);setHistory(h);if(!leftId&&o[0])setLeftId(o[0].id)}).catch(e=>setError(errorMessage(e,'Could not load matchups')))},[user?.id]);
 const all=useMemo(()=>[...own,...pub.filter(p=>!own.some(o=>o.id===p.id))],[own,pub]);const left=all.find(c=>c.id===leftId);const right=all.find(c=>c.id===rightId);const controlled=left&&own.some(o=>o.id===left.id)?left:right&&own.some(o=>o.id===right.id)?right:null;
 if(!user)return <div className="screen"><h2>Sign in to analyze matchups</h2><button className="btn primary" onClick={()=>nav('/login')}>Sign In</button></div>;
 const runProjection=async()=>{if(!left||!right||left.id===right.id)return;const a=analyzeMatchup(characterCombatant(left),characterCombatant(right));setAnalysis(a);try{const saved=await saveMatchup(user.id,left,right,a);if(saved)setHistory(h=>[saved,...h].slice(0,20))}catch(e){setError(errorMessage(e,'Analysis worked, but history could not be saved.'))}};
 const startBattle=async()=>{if(!left||!right||!controlled)return;const opponent=controlled.id===left.id?right:left;try{setError('');setNotice('');const build=await loadOwnedBattleBuild(user.id,controlled);setBattle({left,right,player:controlled,opponent,...build})}catch(e){setError(errorMessage(e,'Could not prepare tactical battle.'))}};
 return <div className="screen social-page page-enter">
  {battle&&<CombatEncounter title={`${battle.player.name} vs ${battle.opponent.name}`} opponent={opponentFromCharacter(battle.opponent)} stats={battle.stats} jutsu={battle.jutsu} equipment={battle.equipment} summon={battle.player.summon||undefined} playerElement={battle.player.chakra_primary||undefined} difficulty={74} onCancel={()=>setBattle(null)} onComplete={async(result:CombatResult)=>{const current=battle;setBattle(null);const actual=applyInteractiveBattleResult(current.left,current.right,current.player.id,result);setAnalysis(actual);try{const saved=await saveMatchup(user.id,current.left,current.right,actual);if(saved)setHistory(h=>[saved,...h].slice(0,20));setNotice(`${actual.winnerName} won the interactive matchup in ${result.rounds} rounds.`)}catch(e){setError(errorMessage(e,'Battle completed, but history could not be saved.'))}}}/>} 
  <PageHeader eyebrow="V11 · SOCIAL" title="Matchup Lab" description="Project profile advantages or take control of one of your own shinobi and fight the matchup turn by turn."/>
  {error&&<div className="generator-error">{error}</div>}{notice&&<div className="generator-notice">{notice}</div>}<SocialTabs active="matchups"/>
  <section className="box"><div className="matchup-builder"><select value={leftId} onChange={e=>{setLeftId(e.target.value);setAnalysis(null)}}><option value="">Choose shinobi…</option>{all.map(c=><option key={c.id} value={c.id}>{c.name}{own.some(o=>o.id===c.id)?' · Mine':' · Public'}</option>)}</select><b>VS</b><select value={rightId} onChange={e=>{setRightId(e.target.value);setAnalysis(null)}}><option value="">Choose opponent…</option>{all.filter(c=>c.id!==leftId).map(c=><option key={c.id} value={c.id}>{c.name}{own.some(o=>o.id===c.id)?' · Mine':' · Public'}</option>)}</select><button className="btn secondary" disabled={!left||!right||left.id===right.id} onClick={runProjection}>Analyze Projection</button><button className="btn primary" disabled={!left||!right||!controlled||left.id===right.id} onClick={()=>void startBattle()}>{controlled?`Fight as ${controlled.name}`:'Own a Shinobi to Fight'}</button></div></section>
  {analysis&&left&&right&&<section className="box matchup-result"><div className="matchup-verdict"><div><small>{left.name}</small><strong>{analysis.leftScore}</strong></div><div><span>{analysis.summary.startsWith('Interactive')?'BATTLE RESULT':'PROJECTED EDGE'}</span><h3>{analysis.winnerName}</h3><p>{analysis.confidence}% confidence</p></div><div><small>{right.name}</small><strong>{analysis.rightScore}</strong></div></div><p className="matchup-summary">{analysis.summary}</p><div className="factor-grid">{analysis.factors.map(f=><div className="factor-row" key={f.label}><strong>{f.label}</strong><span>{f.left}</span><div className="factor-track"><i style={{width:`${Math.max(5,f.left/(f.left+f.right)*100)}%`}}/></div><span>{f.right}</span><small>{f.note}</small></div>)}</div>{analysis.counters.length>0&&<div className="counter-list"><h4>Matchup Interactions</h4>{analysis.counters.map(x=><p key={x}>• {x}</p>)}</div>}<div className="win-condition-grid"><div><h4>{left.name} wins by…</h4>{analysis.winConditions.left.map(x=><p key={x}>+ {x}</p>)}</div><div><h4>{right.name} wins by…</h4>{analysis.winConditions.right.map(x=><p key={x}>+ {x}</p>)}</div></div></section>}
  <section className="box"><SectionHeader eyebrow="HISTORY" title="Recent Matchups"/><div className="match-history">{history.map(h=><article key={h.id}><span>{new Date(h.created_at).toLocaleDateString()}</span><strong>{h.analysis?.winnerName||'Matchup'}</strong><small>{h.analysis?.leftScore ?? '—'} · {h.analysis?.rightScore ?? '—'}</small></article>)}{!history.length&&<EmptyMessage>No matchup history yet.</EmptyMessage>}</div></section>
 </div>;
}

const operationRanks:MissionRank[]=['D','C','B','A','S'];

export function CooperativeMissionsPage(){
 const {user}=useAuth();const nav=useNavigate();const [teams,setTeams]=useState<ShinobiTeam[]>([]);const [teamId,setTeamId]=useState('');const [operations,setOperations]=useState<TeamOperation[]>([]);const [rank,setRank]=useState<MissionRank>('D');const action=useAsyncAction('Squad operation failed');
 const selected=teams.find(t=>t.id===teamId)||null;const [operationPlay,setOperationPlay]=useState(false);
 const refresh=async(id=teamId)=>{if(!user)return;const next=await listTeams(user.id);setTeams(next);const chosen=id||next[0]?.id||'';setTeamId(chosen);setOperations(chosen?await listTeamOperations(chosen):[])};
 useEffect(()=>{void refresh().catch(e=>action.setError(errorMessage(e,'Could not load squad operations')))},[user?.id]);
 useEffect(()=>{if(teamId)void listTeamOperations(teamId).then(setOperations).catch(e=>action.setError(errorMessage(e,'Could not load operation history')))},[teamId]);
 if(!user)return <div className="screen"><PageHeader eyebrow="V11 · PHASE 5" title="Cooperative Missions" description="Deploy multi-shinobi squads into coordinated operations and build team field records."/><button className="btn primary" onClick={()=>nav('/login')}>Sign In</button></div>;
 return <div className="screen page-enter">{operationPlay&&selected&&<ActivityChallenge kind="team" title={`${rank}-Rank · ${selected.name} Operation`} difficulty={{D:42,C:52,B:64,A:76,S:88}[rank]} focus="Command the squad through three coordination drills. Failed field command aborts the deployment before rewards are resolved." onCancel={()=>setOperationPlay(false)} onComplete={async(result:ActivityResult)=>{setOperationPlay(false);if(!result.passed){action.setError(`Squad command failed at ${result.score}. Deployment aborted.`);return;}await action.run(async()=>{const resolved=await deployTeamOperation(teamId,rank);setOperations(await listTeamOperations(teamId));action.setNotice(`${resolved.message} Interactive command ${result.score} · team score ${resolved.team_score}.`)})}}/>}<PageHeader eyebrow="V11 · PHASE 5" title="Cooperative Missions" description="Squad composition now matters in server-resolved missions. Own shinobi receive progression rewards while public allies can strengthen the tactical readout."/><Feedback error={action.error} notice={action.notice}/>
 <SocialTabs active="operations"/>
 <section className="box"><SectionHeader eyebrow="DEPLOYMENT" title={selected?.name||'Choose a squad'} meta={`${teams.length} squads`}/><div className="operation-controls"><select value={teamId} onChange={e=>setTeamId(e.target.value)}><option value="">Choose squad…</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><div className="rank-buttons">{operationRanks.map(r=><button key={r} className={`nav-chip ${rank===r?'active':''}`} onClick={()=>setRank(r)}>{r}-Rank</button>)}</div><button className="btn primary" disabled={!teamId||action.busy} onClick={()=>setOperationPlay(true)}>Enter Operation</button></div><p className="muted">Higher ranks require stronger average owned-shinobi levels. Operations need at least two squad members, can be run once per rank per squad each day, and reward every owned shinobi on the deployed squad.</p></section>
 <section className="box"><SectionHeader eyebrow="FIELD RECORD" title="Squad Operations" meta={`${operations.length} recorded`}/>{!operations.length?<EmptyMessage>No cooperative operations recorded for this squad yet.</EmptyMessage>:<div className="operation-list">{operations.map(o=><article className="operation-card" key={o.id}><div><span className={`rank-badge rank-${o.rank.toLowerCase()}`}>{o.rank}</span><h4>{o.title}</h4><p>{o.objective}</p></div><div className="operation-score"><strong>{o.score}</strong><span>{o.success?'SUCCESS':'WITHDRAWAL'}</span><small>+{o.contribution} contribution</small></div><div className="reward-line"><span>XP +{o.rewards.xp}</span><span>Rep +{o.rewards.reputation}</span><span>TP +{o.rewards.training_points}</span><span>Ryō +{o.rewards.ryo}</span></div></article>)}</div>}</section>
 </div>
}

export function VillageWarsPage(){
 const {user}=useAuth();const nav=useNavigate();const [war,setWar]=useState<VillageWarSeason|null>(null);const [warPlay,setWarPlay]=useState(false);const [standings,setStandings]=useState<VillageWarStanding[]>([]);const [teams,setTeams]=useState<ShinobiTeam[]>([]);const [teamId,setTeamId]=useState('');const [history,setHistory]=useState<VillageWarDeployment[]>([]);const action=useAsyncAction('Village war deployment failed');
 const refresh=async()=>{const [active,board]=await Promise.all([getActiveVillageWar(),listVillageWarStandings()]);setWar(active);setStandings(board);if(user){const next=await listTeams(user.id);setTeams(next);const chosen=teamId||next[0]?.id||'';setTeamId(chosen);setHistory(await listVillageWarDeployments(chosen||undefined))}};
 useEffect(()=>{void refresh().catch(e=>action.setError(errorMessage(e,'Could not load village war')))},[user?.id]);
 useEffect(()=>{if(user&&teamId)void listVillageWarDeployments(teamId).then(setHistory).catch(()=>{})},[teamId]);
 return <div className="screen page-enter">{warPlay&&<ActivityChallenge kind="war" title="Village War Frontline" difficulty={82} focus="Coordinate the frontline maneuver. Your squad deploys only if you clear the command challenge." onCancel={()=>setWarPlay(false)} onComplete={async(result:ActivityResult)=>{setWarPlay(false);if(!result.passed){action.setError(`Frontline command failed at ${result.score}. No deployment was committed.`);return;}await action.run(async()=>{const resolved=await deployVillageWarTeam(teamId);await refresh();action.setNotice(`${resolved.message} Command ${result.score} · +${resolved.war_points} war points.`)})}}/>}<PageHeader eyebrow="V11 · PHASE 5" title="Village Wars" description="Deploy village-aligned squads into a shared seasonal front. Daily team operations add war points to your village's global standing."/><Feedback error={action.error} notice={action.notice}/><SocialTabs active="wars"/>
 <section className="box"><SectionHeader eyebrow="ACTIVE FRONT" title={war?.name||'No active village war'} meta={war?`Ends ${new Date(war.ends_at).toLocaleDateString()}`:'Stand by'}/><div className="war-standings">{standings.map(row=><article className={`war-row rank-${row.rank}`} key={row.village_id}><strong>#{row.rank}</strong><div><h4>{row.village_id}</h4><p>{row.deployments} deployments · {row.victories} victories</p></div><b>{row.war_points} WP</b></article>)}</div></section>
 {user?<section className="box"><SectionHeader eyebrow="WAR DEPLOYMENT" title="Commit a Village Squad" meta="1 deployment / squad / day"/><div className="operation-controls"><select value={teamId} onChange={e=>setTeamId(e.target.value)}><option value="">Choose squad…</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button className="btn primary" disabled={!teamId||!war||action.busy} onClick={()=>setWarPlay(true)}>Enter Frontline</button></div><p className="muted">A war squad needs at least two of your own shinobi serving the same village. Successful deployments reward TP, Ryō, village reputation, and shared war points.</p>{history.length>0&&<div className="war-history">{history.slice(0,8).map(d=><div key={d.id}><span>{new Date(d.created_at).toLocaleDateString()}</span><strong>{d.village_id}</strong><b>{d.success?'Victory':'Repelled'} · +{d.war_points} WP</b></div>)}</div>}</section>:<section className="box"><h3>Join the war effort</h3><p className="muted">Sign in to deploy one of your village-aligned squads.</p><button className="btn primary" onClick={()=>nav('/login')}>Sign In</button></section>}
 </div>
}
