import {useEffect,useMemo,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {useAuth} from '../contexts/AuthContext';
import {useArchive} from '../store/useArchive';
import {listCharacters,type ShinobiCharacter} from '../services/characterService';
import {listPublicCharacters} from '../services/publicProfileService';
import {addTeamMember,createTeam,deleteTeam,listTeamMembers,listTeams,removeTeamMember,updateTeam} from '../services/socialService';
import type {ShinobiTeam,ShinobiTeamMember} from '../types/social';
import {analyzeTeam,characterCombatant} from '../utils/socialCombat';

export function TeamsPage(){
 const {user}=useAuth();const nav=useNavigate();const {activeCharacterId}=useArchive();
 const [teams,setTeams]=useState<ShinobiTeam[]>([]);const [selectedId,setSelectedId]=useState<string>('');const [members,setMembers]=useState<ShinobiTeamMember[]>([]);const [own,setOwn]=useState<ShinobiCharacter[]>([]);const [publicChars,setPublicChars]=useState<ShinobiCharacter[]>([]);const [name,setName]=useState('');const [description,setDescription]=useState('');const [candidate,setCandidate]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 const selected=teams.find(t=>t.id===selectedId)||null;
 const refreshTeams=async()=>{if(!user)return;const next=await listTeams(user.id);setTeams(next);if(!selectedId&&next[0])setSelectedId(next[0].id)};
 const refreshMembers=async()=>{if(!selectedId){setMembers([]);return;}setMembers(await listTeamMembers(selectedId))};
 useEffect(()=>{if(!user)return;Promise.all([listTeams(user.id),listCharacters(user.id),listPublicCharacters(40)]).then(([t,o,p])=>{setTeams(t);setOwn(o);setPublicChars(p);const id=t[0]?.id||'';setSelectedId(id)}).catch(e=>setError(e instanceof Error?e.message:'Could not load teams'))},[user?.id]);
 useEffect(()=>{void refreshMembers()},[selectedId]);
 useEffect(()=>{if(selected){setName(selected.name);setDescription(selected.description||'')}},[selected?.id]);
 const analysis=useMemo(()=>analyzeTeam(members.flatMap(m=>m.character?[characterCombatant(m.character)]:[])),[members]);
 const available=useMemo(()=>{const ids=new Set(members.map(m=>m.character_id));const merged=[...own,...publicChars.filter(p=>!own.some(o=>o.id===p.id))];return merged.filter(c=>!ids.has(c.id))},[own,publicChars,members]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await fn();await refreshTeams();await refreshMembers()}catch(e){setError(e instanceof Error?e.message:'Team action failed')}finally{setBusy(false)}};
 if(!user)return <div className="screen"><h2>Sign in to build squads</h2><p className="lede">Teams, rivals and matchup history belong to your account.</p><button className="btn primary" onClick={()=>nav('/login')}>Sign In</button></div>;
 return <div className="screen social-page page-enter"><div className="dash-head"><div><span className="eyebrow">V10 · PHASE 3</span><h2>Shinobi Teams</h2></div><p>Build squads from your own shinobi and public profiles. V10 analyzes coverage, cohesion and battlefield roles.</p></div>{error&&<div className="generator-error">{error}</div>}{notice&&<div className="generator-notice">{notice}</div>}
 <div className="social-tabs"><button className="active">Teams</button><button onClick={()=>nav('/rivals')}>Rivals</button><button onClick={()=>nav('/matchups')}>Matchups</button></div>
 <div className="team-layout"><aside className="box team-sidebar"><div className="section-title"><div><span className="eyebrow">YOUR SQUADS</span><h3>{teams.length} Teams</h3></div><button className="mini-link" onClick={()=>run(async()=>{const t=await createTeam(user.id,`Squad ${teams.length+1}`);setSelectedId(t.id);setNotice('New squad created.')})}>+ New</button></div>{teams.map(t=><button className={`team-select ${selectedId===t.id?'active':''}`} key={t.id} onClick={()=>setSelectedId(t.id)}><strong>{t.name}</strong><span>{t.description||'No description yet'}</span></button>)}{!teams.length&&<p className="muted">Create your first squad.</p>}</aside>
 <div className="team-main">{selected?<><section className="box"><div className="section-title"><div><span className="eyebrow">SQUAD PROFILE</span><h3>{selected.name}</h3></div><button className="mini-link danger" onClick={()=>{if(confirm(`Delete ${selected.name}?`))void run(async()=>{await deleteTeam(user.id,selected.id);setSelectedId('')})}}>Delete</button></div><div className="team-editor"><input value={name} maxLength={60} onChange={e=>setName(e.target.value)} placeholder="Squad name"/><textarea value={description} maxLength={280} onChange={e=>setDescription(e.target.value)} placeholder="Squad purpose or description…"/><button className="btn secondary" disabled={busy} onClick={()=>run(async()=>{await updateTeam(user.id,selected.id,name,description);setNotice('Squad updated.')})}>Save Squad</button></div></section>
 <section className="box"><div className="section-title"><div><span className="eyebrow">MEMBERS</span><h3>{members.length}/4 Shinobi</h3></div></div><div className="team-member-grid">{members.map((m,i)=><article className="team-member" key={m.id}><div className="team-member-avatar">{m.character?.portrait_url?<img src={m.character.portrait_url} alt=""/>:<span>忍</span>}</div><div><small>SLOT {i+1}</small><h4>{m.character?.name||'Unknown Shinobi'}</h4><p>{[m.character?.clan,m.character?.village,m.character?.role].filter(Boolean).join(' · ')}</p></div><button className="mini-link danger" onClick={()=>run(async()=>{await removeTeamMember(m.id)})}>Remove</button></article>)}{members.length<4&&<div className="team-add"><select value={candidate} onChange={e=>setCandidate(e.target.value)}><option value="">Choose shinobi…</option>{available.map(c=><option value={c.id} key={c.id}>{c.name}{c.user_id===user.id?' · Mine':' · Public'}</option>)}</select><button className="btn primary" disabled={!candidate||busy} onClick={()=>run(async()=>{await addTeamMember(selected.id,candidate);setCandidate('');setNotice('Shinobi added to squad.')})}>Add Member</button></div>}</div></section>
 {members.length>0&&<section className="box"><div className="section-title"><div><span className="eyebrow">SQUAD ANALYSIS</span><h3>Team Readout</h3></div><strong>{analysis.rating}/100</strong></div><div className="team-metrics"><div><span>COHESION</span><strong>{analysis.cohesion}</strong></div><div><span>COVERAGE</span><strong>{analysis.coverage}</strong></div><div><span>LEADERSHIP</span><strong>{analysis.leadership}</strong></div></div><div className="team-analysis-grid"><div><h4>Strengths</h4>{analysis.strengths.map(x=><p key={x}>+ {x}</p>)}</div><div><h4>Pressure Points</h4>{analysis.weaknesses.map(x=><p key={x}>− {x}</p>)}</div></div><div className="role-list"><h4>Suggested Roles</h4>{analysis.roleAssignments.map(r=><div key={r.characterId}><strong>{r.name}</strong><span>{r.role}</span></div>)}</div></section>}</>:<div className="box"><h3>Create a squad</h3><p className="muted">Add up to four shinobi and V10 will analyze the team's composition.</p></div>}</div></div>
 </div>
}
